In [1]:
import pandas as pd
import csv

In [11]:
song_data = pd.read_csv(""")
song_data.head()

,Track,Composer,Milliseconds,Bytes,UnitPrice,Genre,Album,Artist
0,All the Best Cowboys Have Daddy Issues,NaN,2555492,211743651,1.99,TV Shows,"Lost, Season 1",Lost
1,Beira Mar,Gilberto Gil,295444,9597994,0.99,Latin,Unplugged,Eric Clapton
2,Brasil,"Milton Nascimento, Fernando Brant",155428,5252560,0.99,Latin,Milton Nascimento Ao Vivo,Milton Nascimento
3,Ben Franklin,NaN,1271938,264168080,1.99,Comedy,"The Office, Season 3",The Office
4,O Último Romântico (Ao Vivo),NaN,231993,7692697,0.99,Latin,Lulu Santos - RCA 100 Anos De Música - Álbum 02,Lulu Santos

#### Delete column titled "Composer"

In [12]:
song_data.drop(columns="Composer")

,Track,Milliseconds,Bytes,UnitPrice,Genre,Album,Artist
0,All the Best Cowboys Have Daddy Issues,2555492,211743651,1.99,TV Shows,"Lost, Season 1",Lost
1,Beira Mar,295444,9597994,0.99,Latin,Unplugged,Eric Clapton
2,Brasil,155428,5252560,0.99,Latin,Milton Nascimento Ao Vivo,Milton Nascimento
3,Ben Franklin,1271938,264168080,1.99,Comedy,"The Office, Season 3",The Office
4,O Último Romântico (Ao Vivo),231993,7692697,0.99,Latin,Lulu Santos - RCA 100 Anos De Música - Álbum 02,Lulu Santos
...,...,...,...,...,...,...,...
298,She Loves Me Not,209867,6887544,0.99,Alternative & Punk,Album Of The Year,Faith No More
299,Beth,170187,5577807,0.99,Rock,Unplugged [Live],Kiss
300,Exploder,206053,4948095,0.99,Rock,Audioslave,Audioslave
301,Os Cegos Do Castelo,296829,9868187,0.99,Alternative & Punk,Acústico,Titãs
302,The Star Spangled Banner,43232,1385810,0.99,Rock,Rattle And Hum,U2

#### How many songs cost more than a dollar?

In [14]:
song_data["UnitPrice"].unique()

array([1.99, 0.99])

In [22]:
price_group = song_data.groupby("UnitPrice")
above_1dollar = price_group.get_group(1.99)
above_1dollar.count()  #is there a more aestheticly pleasing way to display the number of tracks?

Track           13
Composer         0
Milliseconds    13
Bytes           13
UnitPrice       13
Genre           13
Album           13
Artist          13
dtype: int64

#### Find most repeated three-letter word

In [43]:
prepositions = ["as", "at", "but", "by", "down", "for", "from", "in", "into", "like", "near", "next", "of", "off", "on", "onto", "out", "over", "past", "plus", "minus", "since", "than", "to", "up", "with"]
common_words = ["I", "me", "us", "we", "you", "they", "them", "the", "The", "You", "And"]
word_list = []
for name in song_data["Track"]: 
    temp_list = name.split()
    for word in temp_list:
        if word not in prepositions and word not in common_words:
            if len(word)==3:
                word_list.append(word)
def most_frequent(List):
    return max(set(List), key = List.count)
most_common_word = most_frequent(word_list)
frequency = word_list.count("Man")
print("The most common three-letter word on Track titles is '"+most_common_word+"', appearing a total of "+str(frequency)+" times.")

The most common three-letter word on Track titles is 'Man', appearing a total of 5 times.

#### Filter all tracks that have 'TV Show' as a genre

In [49]:
genre = song_data.groupby("Genre")
genre.count() #como hacer si solo quiero que salga the trak column?

,Track,Composer,Milliseconds,Bytes,UnitPrice,Album,Artist
Genre,,,,,,,
Alternative,2,0,2,2,2,2,2
Alternative & Punk,40,33,40,40,40,40,40
Blues,3,3,3,3,3,3,3
Bossa Nova,2,0,2,2,2,2,2
Classical,5,4,5,5,5,5,5
Comedy,3,0,3,3,3,3,3
Drama,2,0,2,2,2,2,2
Easy Listening,1,1,1,1,1,1,1
Electronica/Dance,1,1,1,1,1,1,1
Heavy Metal,2,2,2,2,2,2,2
Hip Hop/Rap,4,1,4,4,4,4,4
Jazz,21,13,21,21,21,21,21
Latin,51,24,51,51,51,51,51
Metal,28,27,28,28,28,28,28
Pop,3,2,3,3,3,3,3
R&B/Soul,5,5,5,5,5,5,5
Reggae,3,2,3,3,3,3,3
Rock,114,105,114,114,114,114,114
Sci Fi & Fantasy,2,0,2,2,2,2,2
Soundtrack,3,2,3,3,3,3,3
TV Shows,6,0,6,6,6,6,6
World,2,2,2,2,2,2,2

In [50]:
song_data[song_data.Genre == "TV Shows"]

,Track,Composer,Milliseconds,Bytes,UnitPrice,Genre,Album,Artist
0,All the Best Cowboys Have Daddy Issues,NaN,2555492,211743651,1.99,TV Shows,"Lost, Season 1",Lost
23,Confidence Man,NaN,2615244,223756475,1.99,TV Shows,"Lost, Season 1",Lost
38,Diwali,NaN,1279904,252726644,1.99,TV Shows,"The Office, Season 3",The Office
148,The 23rd Psalm,NaN,2610416,487401604,1.99,TV Shows,"Lost, Season 2",Lost
209,"Lost (Pilot, Part 2)",NaN,2436583,204995876,1.99,TV Shows,"Lost, Season 1",Lost
279,Numbers,NaN,2609772,214709143,1.99,TV Shows,"Lost, Season 1",Lost